// <auto-generated />
using System;
using AihrlyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace aihrly_api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260427111858_DBEnumSchemaFixes")]
    partial class DBEnumSchemaFixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "application_note_type", new[] { "general", "screening", "interview", "reference_check", "red_flag" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "application_stages", new[] { "applied", "screening", "interview", "offer", "hired", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "score_dimension", new[] { "culture_fit", "interview", "assessment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status", new[] { "open", "closed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "team_member_role", new[] { "recruiter", "hiring_manager" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AihrlyApi.Entities.Application", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("coverLetter")
                        .HasColumnType("text");

                    b.Property<string>("current_stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("jobId")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("current_stage");

                    b.HasIndex("jobId");

                    b.HasIndex("email", "jobId")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("AihrlyApi.Entities.ApplicationNote", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("applicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("created_by")
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("applicationId");

                    b.HasIndex("created_by");

                    b.ToTable("ApplicationNotes");
                });

            modelBuilder.Entity("AihrlyApi.Entities.ApplicationScore", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("applicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<string>("dimension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("updatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("updatedBy");

                    b.HasIndex("applicationId", "dimension")
                        .IsUnique();

                    b.ToTable("ApplicationScore");
                });

            modelBuilder.Entity("AihrlyApi.Entities.ApplicationStageHistory", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("applicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("changed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("changed_by")
                        .HasColumnType("uuid");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("from_stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("to_stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("applicationId");

                    b.HasIndex("changed_by");

                    b.ToTable("ApplicationStageHistories");
                });

            modelBuilder.Entity("AihrlyApi.Entities.Job", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("status");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("AihrlyApi.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            id = new Guid("00000000-0000-0000-0000-000000000001"),
                            email = "noahboye@mail.com",
                            name = "Noah Boye",
                            role = "hiring_manager"
                        });
                });

            modelBuilder.Entity("AihrlyApi.Entities.Application", b =>
                {
                    b.HasOne("AihrlyApi.Entities.Job", "job")
                        .WithMany("applications")
                        .HasForeignKey("jobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("job");
                });

            modelBuilder.Entity("AihrlyApi.Entities.ApplicationNote", b =>
                {
                    b.HasOne("AihrlyApi.Entities.Application", null)
                        .WithMany("notes")
                        .HasForeignKey("applicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AihrlyApi.Entities.TeamMember", "teamMember")
                        .WithMany()
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("teamMember");
                });

            modelBuilder.Entity("AihrlyApi.Entities.ApplicationScore", b =>
                {
                    b.HasOne("AihrlyApi.Entities.Application", null)
                        .WithMany("scores")
                        .HasForeignKey("applicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AihrlyApi.Entities.TeamMember", "teamMember")
                        .WithMany()
                        .HasForeignKey("updatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("teamMember");
                });

            modelBuilder.Entity("AihrlyApi.Entities.ApplicationStageHistory", b =>
                {
                    b.HasOne("AihrlyApi.Entities.Application", null)
                        .WithMany("stage_history")
                        .HasForeignKey("applicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AihrlyApi.Entities.TeamMember", "teamMember")
                        .WithMany()
                        .HasForeignKey("changed_by")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("teamMember");
                });

            modelBuilder.Entity("AihrlyApi.Entities.Application", b =>
                {
                    b.Navigation("notes");

                    b.Navigation("scores");

                    b.Navigation("stage_history");
                });

            modelBuilder.Entity("AihrlyApi.Entities.Job", b =>
                {
                    b.Navigation("applications");
                });
#pragma warning restore 612, 618
        }
    }
}
